### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by shawn613** [teprinciple/MailSender#1]
大神你好，用到你的发送邮件功能，但是运行到transport.connect();
                        transport.sendMessage(msg, addresses);这里时候，就抛异常了，请教下改如何处理，发送的邮件地址密码我已经更为为自己的了

**Comment by teprinciple** [comment]
@mingyuemyheart 确认你邮箱的  POP3/SMTP 以及 IMAP/SMTP服务是否开启

**Comment by shawn613** [comment]
开启了，发送邮箱和接收邮箱都开启了

**Comment by shawn613** [comment]
用的都是qq邮箱

**Comment by teprinciple** [comment]
@mingyuemyheart 加q  2584770373  我帮你看看

**Comment by shawn613** [comment]
@@问题已解决，这里要特别感谢大神@teprinciple 帮忙查询问题，后来的小伙伴们请注意：
1.请确认发送的邮箱是否开启POP3/SMTP服务及IMAP/SMTP服务（请注意qq邮箱的按钮有歧义，检查好）
2.替换发送邮箱账号和授权码（注意不是登录邮箱密码，而是授权POP3/SMTP服务授权码）

**Comment by appdev** [comment]
我改了之后还是抛异常 说是timeout
